language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "moviebox";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup

deploy:
  branch: main
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: m0vieb0x
  api_key: 
    secure: tKg+ltThDLCDlDS8TFUtvy4xpTkhx8qQcCIXL+ZKTay6+nyB+dQF9m9d8DTQqpWe6522QlAQ8cfxl2OVMRNFnkjvwMwcL++sTd6DPPDlLTKCe8M8AR7MQ1ma9S1nSLFYrCavt09bEHUX5ssLfGqLBrzRBCciqcubIVFROt2ge3LaER/DPL5SGslwyORZmQpF25qAbjdTz1Z9P2JMnNE7vViRLPK/QE4GzZ1AosZMdy75PkO8C+r6j9dtAT7neWvrRMXWjgMBYADc2oIOHHj4sTlxQyWFNx6qRQnSY88GjQx+OjfeDC/kuM6oHVGp//2397ojmB83yACW8boY5YO4kPrhpspSMI0iXlgnkBnaSmjtrK8gyULcRlsaRc9NEeqc3bGbTJZtqDAIDbpUPxPxZy0Y6Irn81CGAX216OrzEd6GyZCzH7Q57Z93xibXJAkXspvLikghKX0/dIdn93+0qkja5SRNKPCjE3mqJzvYvZLwRTV57Gt8jw/Z6f2bzOS6ZrlPMxiZi/5Lpa8EuSEVIql1My6ob2G82btZrWm5WaznI8jxe0ybnAIBu/rzCQOqfI7tq9roloCXPJQG4fEHNIuC30wQE534xWeHncw6zBGiVv7BYnmTnvu+cpH/AV4DwqgfZQpn5L6hLfP4Q0W1UrG2fcRe2WgM6nacswA1RQw=